'use client';

import Image from 'next/image';
import { ArrowUpRight, ChevronDown, Coffee, HeartHandshake, MapPin, Menu, Play, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import { useState } from 'react';

const applyUrl = 'https://waymart.selfrecruit.ge/e8e7ca79-c3fc-475c-9c01-bfde96354572';

export default function Home() {
  const [open, setOpen] = useState(false);
  return <main>
    <nav className="nav"><a className="logo" href="#top" aria-label="Way Mart"><span className="logo-w">W</span><span className="logo-copy"><b>ვეი მარტი</b><small>WAY MART</small></span></a><div className={open ? 'nav-links open' : 'nav-links'}><a href="#way">ბრენდი</a><a href="#people">გუნდი</a><a href="#roles">ვაკანსიები</a><a href="#life">ჩვენი გარემო</a><a className="nav-apply" href={applyUrl} target="_blank">შემოგვიერთდი <ArrowUpRight size={16}/></a></div><button className="menu" onClick={() => setOpen(!open)} aria-label="მენიუ">{open ? <X/> : <Menu/>}</button></nav>

    <section className="hero" id="top"><div className="hero-content"><p className="kicker"><span/> კარიერა Way Mart-ში</p><h1>გზაზე მეგობრობა<br/><em>ადამიანებით იწყება.</em></h1><p className="hero-copy">შენი ენერგია, შენი ხასიათი, შენი გზა. გახდი გუნდის ნაწილი, რომელიც ყოველდღე ათასობით ადამიანს აძლევს სწრაფ, გემრიელ და კარგ გამოცდილებას.</p><div className="hero-actions"><a className="button red" href={applyUrl} target="_blank">ნახე ღია პოზიციები <ArrowUpRight size={18}/></a><a className="text-link" href="#way">გაიცანი Way Mart <ChevronDown size={18}/></a></div></div><div className="hero-image"><Image src="/media/waymart-storefront.jpg" alt="Way Mart-ის მარკეტი ქალაქში" fill priority sizes="(max-width: 900px) 100vw, 48vw"/><div className="hero-sticker">შენი<br/><strong>მეგობარი</strong><br/>გზაზე<span>✳</span></div><div className="hero-caption"><span className="live-dot"/> 70+ ლოკაცია საქართველოში</div></div><div className="hero-marquee"><span>COFFEE</span><span>FOOD</span><span>PEOPLE</span><span>ENERGY</span><span>WAY MART</span></div></section>

    <section className="intro" id="way"><div className="eyebrow">01 / ჩვენი სამყარო</div><div className="intro-grid"><h2>Way Mart არის ადგილი,<br/><span>სადაც გზა გრძელდება.</span></h2><div><p className="large-copy">ჩვენ SOCAR-ის 70-ზე მეტ სადგურზე ვქმნით იმ პატარა გაჩერებას, რომელიც გზას უკეთესს ხდის.</p><p>იტალიური ყავა, სწრაფი კვება, გამორჩეული პროდუქტები და გუნდი, რომელიც სტუმარს ყოველთვის ამჩნევს. ჩვენთვის მარკეტი მხოლოდ თაროები და სალარო არ არის — ეს არის ადამიანების ენერგია.</p><a className="outline-link" href="https://sgp.ge/way-mart" target="_blank">გაიგე მეტი ბრენდის შესახებ <ArrowUpRight size={17}/></a></div></div><div className="value-row"><div><Coffee/><b>გემო, რომელსაც იმახსოვრებენ</b><span>იტალიური ყავა და სწრაფი კვება</span></div><div><Sparkles/><b>ყოველდღე ახალი რიტმი</b><span>აქ არასდროს არის ორი ერთნაირი დღე</span></div><div><HeartHandshake/><b>ადამიანი ცენტრში</b><span>სტუმრისთვის და გუნდისთვის</span></div></div></section>

    <section className="people" id="people"><div className="people-art"><Image src="/media/waymart-story-1.avif" alt="Way Mart-ის გარემო" fill sizes="(max-width: 900px) 100vw, 50vw"/><div className="play"><Play fill="currentColor" size={22}/></div></div><div className="people-copy"><div className="eyebrow light">02 / ადამიანები</div><h2>ყველა კარგ ცვლას<br/><em>კარგი გუნდი ქმნის.</em></h2><p>ჩვენს მარკეტებში შეხვდები ადამიანებს, რომლებსაც უყვართ მოძრაობა, ურთიერთობა და ის მომენტი, როცა სტუმარი კმაყოფილი გადის.</p><blockquote>“აქ ყველაზე მეტად ის მომწონს, რომ ჩემი დღე ყოველთვის ადამიანებით არის სავსე — და თითოეულ მათგანს რაღაცას ვუტოვებ.”<cite>— Way Mart-ის გუნდის წევრი</cite></blockquote><a className="light-link" href="#life">ნახე ჩვენი სამუშაო ცხოვრება <ArrowUpRight size={17}/></a></div></section>

    <section className="roles" id="roles"><div className="eyebrow">03 / შენი შემდეგი ნაბიჯი</div><div className="roles-head"><h2>იპოვე როლი,<br/><em>რომელიც შენ გგავს.</em></h2><a className="button dark" href={applyUrl} target="_blank">ყველა ვაკანსიის ნახვა <ArrowUpRight size={18}/></a></div><div className="role-list"><Role icon={<Users/>} title="მოლარე-კონსულტანტი" meta="ფილიალები · თბილისი და რეგიონები" text="სტუმართან ურთიერთობა, პროდუქტის წარმოჩენა და Way Mart-ის ატმოსფეროს შექმნა."/><Role icon={<ShieldCheck/>} title="საწყობის ადმინისტრატორი" meta="ლოჯისტიკა · რეგიონები" text="სისწრაფე, სიზუსტე და გუნდისთვის საჭირო ყველაფრის დროულად მომზადება."/><Role icon={<MapPin/>} title="რეგიონალური მენეჯერი" meta="ოპერაციები · თბილისი" text="ადამიანების, სტანდარტების და შედეგების მართვა 70+ ლოკაციის ქსელში."/></div></section>

    <section className="life" id="life"><div className="life-top"><div className="eyebrow light">04 / სამუშაო ცხოვრების კადრები</div><h2>აქ ყოველდღე<br/><em>რაღაც ხდება.</em></h2><p>Way Mart-ის გარემო ენერგიულია, ნამდვილია და ადამიანებით არის სავსე.</p></div><div className="gallery"><div className="gallery-main"><Image src="/media/waymart-story-2.avif" alt="Way Mart-ის გუნდი" fill sizes="(max-width: 900px) 100vw, 45vw"/></div><div className="gallery-small"><Image src="/media/waymart-storefront.jpg" alt="Way Mart-ის სივრცე" fill sizes="(max-width: 900px) 100vw, 25vw"/></div><div className="gallery-note"><span>WAY MART</span><b>მოდი, შენი<br/>ისტორია<br/>აქ დაწერე.</b><a href={applyUrl} target="_blank">შემოგვიერთდი <ArrowUpRight size={17}/></a></div></div></section>

    <section className="benefits"><div className="eyebrow">05 / რას მიიღებ</div><div className="benefit-grid"><div><span>01</span><h3>ზრდის გზა</h3><p>პოზიციიდან პოზიციამდე — ისწავლე, გაიზარდე და შექმენი შენი კარიერული მიმართულება.</p></div><div><span>02</span><h3>შენი კეთილდღეობა</h3><p>ჯანმრთელობის დაზღვევა, ტრანსპორტირების მხარდაჭერა და ბონუსური შესაძლებლობები.</p></div><div><span>03</span><h3>დიდი ქსელის გამოცდილება</h3><p>ისწავლე საცალო ვაჭრობის ყველაზე ცოცხალ გარემოში, პროფესიონალ გუნდთან ერთად.</p></div></div></section>

    <section className="final-cta"><div><div className="eyebrow light">შენი გზა შეიძლება აქ გაგრძელდეს</div><h2>მზად ხარ<br/><em>შემოგვიერთდე?</em></h2></div><a className="button red large" href={applyUrl} target="_blank">შეავსე განაცხადი <ArrowUpRight size={20}/></a></section>
    <footer><a className="logo" href="#top"><span className="logo-w">W</span><span className="logo-copy"><b>ვეი მარტი</b><small>WAY MART</small></span></a><span>© 2026 Way Mart · შენი მეგობარი გზაზე</span><div><a href="https://www.facebook.com/WayMartGeorgia/" target="_blank">Facebook</a><a href="https://www.tiktok.com/@waymart" target="_blank">TikTok</a></div></footer>
  </main>;
}

function Role({icon,title,meta,text}:{icon:React.ReactNode,title:string,meta:string,text:string}) { return <article className="role-card"><div className="role-icon">{icon}</div><div><small>{meta}</small><h3>{title}</h3><p>{text}</p></div><a href={applyUrl} target="_blank" aria-label={`${title}-ზე განაცხადი`}><ArrowUpRight size={20}/></a></article>; }
