'use client';
import Image from 'next/image';
import { ArrowDownRight, ArrowUpRight, Menu, X } from 'lucide-react';
import { useState } from 'react';

const applyUrl='https://waymart.selfrecruit.ge/e8e7ca79-c3fc-475c-9c01-bfde96354572';
export default function Home(){const [menu,setMenu]=useState(false);return <main className="new-site">
<header className="topbar"><a className="wordmark" href="#start"><span className="mark">W</span><span>WAY<br/><b>MART</b></span></a><div className="location">CAREERS / GEORGIA</div><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="მენიუ">{menu?<X/>:<Menu/>}</button><nav className={menu?'menu-panel show':'menu-panel'}><a href="#why">Why Way Mart</a><a href="#roles">Open roles</a><a href="#inside">Inside the shift</a><a href={applyUrl} target="_blank">Apply now <ArrowUpRight size={15}/></a></nav></header>
<section className="opening" id="start"><div className="vertical-note">A FRIEND ON THE WAY <span>✦</span></div><div className="opening-copy"><p className="micro">WAY MART / PEOPLE FIRST</p><h1>Find your<br/><i>pace.</i></h1><p className="opening-lead">სწრაფი დღეები. ნამდვილი ადამიანები.<br/>საქმე, რომელსაც გზაზე მოჰყვება.</p><a className="circle-cta" href="#roles"><span>ნახე<br/>პოზიციები</span><ArrowDownRight size={24}/></a></div><div className="opening-photo"><Image src="/media/waymart-storefront.jpg" alt="Way Mart-ის მარკეტი" fill priority sizes="(max-width: 800px) 100vw, 52vw"/><div className="photo-label">01 / YOUR<br/>NEXT STOP</div></div><div className="scroll-mark">SCROLL TO EXPLORE ↓</div></section>
<section className="statement" id="why"><div className="section-index">02</div><div className="statement-main"><p className="micro">MORE THAN A MARKET</p><h2>ჩვენ ვქმნით<br/><span>გაჩერების<br/>მომენტებს.</span></h2></div><div className="statement-side"><p>Way Mart არის ადგილი გზაზე, სადაც სწრაფი ყავა, საჭირო პროდუქტი და კარგი სიტყვა ერთ გამოცდილებად იკვრება.</p><p>70-ზე მეტ SOCAR-ის სადგურზე ჩვენი გუნდი ყოველდღე ხვდება ათასობით ადამიანს — და თითოეული შეხვედრა მნიშვნელოვანია.</p><a className="arrow-link" href="https://sgp.ge/way-mart" target="_blank">Way Mart-ის ამბავი <ArrowUpRight size={18}/></a></div></section>
<section className="manifesto"><div className="manifesto-image"><Image src="/media/waymart-story-1.avif" alt="Way Mart-ის სამუშაო გარემო" fill sizes="50vw"/><span>THE<br/>EVERYDAY<br/>ENERGY</span></div><div className="manifesto-list"><p className="micro">03 / THE WAY WE WORK</p><Manifesto n="01" t="Be present" p="შეამჩნიე სტუმარი. მოუსმინე გუნდს. შენი ყურადღება იგრძნობა."/><Manifesto n="02" t="Move together" p="ცვლა გუნდური რიტმია — როცა ერთმანეთს ეხმარები, ყველაფერი სწრაფად მიდის."/><Manifesto n="03" t="Make it better" p="პატარა გაუმჯობესებები ქმნის დიდ გამოცდილებას — თაროზე, სალაროსთან და გუნდში."/></div></section>
<section className="roles-new" id="roles"><div className="roles-intro"><p className="micro">04 / YOUR PLACE HERE</p><h2>What will<br/><i>you bring?</i></h2><p>აირჩიე როლი და დაიწყე იქ, სადაც შენი ხასიათი და ენერგია ყველაზე მეტად გამოგადგება.</p></div><div className="role-rail"><Role n="01" t="მოლარე-კონსულტანტი" d="თბილისი · რეგიონები"/><Role n="02" t="საწყობის ადმინისტრატორი" d="ლოჯისტიკა · ოპერაციები"/><Role n="03" t="რეგიონალური მენეჯერი" d="ლიდერობა · ზრდა"/><a className="see-all" href={applyUrl} target="_blank">ყველა<br/>ვაკანსია <ArrowUpRight size={20}/></a></div></section>
<section className="shift" id="inside"><div className="shift-title"><p className="micro">05 / INSIDE THE SHIFT</p><h2>One day.<br/><i>Many stories.</i></h2></div><div className="shift-collage"><div className="collage-large"><Image src="/media/waymart-story-2.avif" alt="Way Mart-ის გუნდი" fill sizes="45vw"/><span>TEAM / 01</span></div><div className="collage-small"><Image src="/media/waymart-storefront.jpg" alt="Way Mart-ის ლოკაცია" fill sizes="25vw"/><span>PLACE / 02</span></div><div className="collage-copy">ყოველი ცვლა განსხვავებულია.<br/><strong>შენი ისტორია აქ იწყება.</strong></div></div></section>
<section className="join"><div className="join-top"><p className="micro">06 / TAKE THE NEXT STEP</p><span>READY WHEN<br/>YOU ARE.</span></div><h2>მოდი,<br/><i>გზაზე</i> შევხვდეთ.</h2><a className="apply-stamp" href={applyUrl} target="_blank">შეავსე<br/>განაცხადი <ArrowUpRight size={24}/></a></section>
<footer><a className="wordmark" href="#start"><span className="mark">W</span><span>WAY<br/><b>MART</b></span></a><span>შენი მეგობარი გზაზე</span><div><a href="https://www.facebook.com/WayMartGeorgia/" target="_blank">FB</a><a href="https://www.tiktok.com/@waymart" target="_blank">TT</a></div></footer></main>}
function Role({n,t,d}:{n:string,t:string,d:string}){return <a className="role-line" href={applyUrl} target="_blank"><b>{n}</b><span><strong>{t}</strong><small>{d}</small></span><ArrowUpRight size={19}/></a>}
function Manifesto({n,t,p}:{n:string,t:string,p:string}){return <div className="manifesto-row"><b>{n}</b><div><h3>{t}</h3><p>{p}</p></div></div>}
