'use client';
import Image from 'next/image';
import { ArrowDownRight, ArrowUpRight, Menu, X } from 'lucide-react';
import { useState } from 'react';

const applyUrl='https://waymart.selfrecruit.ge/e8e7ca79-c3fc-475c-9c01-bfde96354572';
export default function Home(){const [menu,setMenu]=useState(false);return <main className="new-site">
<header className="topbar"><a className="wordmark" href="#start"><span className="mark">W</span><span>WAY<br/><b>MART</b></span></a><div className="location">CAREERS / GEORGIA</div><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="მენიუ">{menu?<X/>:<Menu/>}</button><nav className={menu?'menu-panel show':'menu-panel'}><a href="#why">Why Way Mart</a><a href="#roles">Open roles</a><a href="#inside">Inside the shift</a><a href={applyUrl} target="_blank">Apply now <ArrowUpRight size={15}/></a></nav></header>
<section className="opening" id="start"><div className="vertical-note">A FRIEND ON THE WAY <span>✦</span></div><div className="opening-copy"><p className="micro">WAYMART RECRUIT & WIN</p><h1>სამი<br/><i>დატრიალება.</i></h1><p className="opening-lead">გახდი Way Mart-ის გუნდის წევრი და მოიგე 50₾-იანი ვაუჩერი. კარგი ამბავი აქ იწყება.</p><a className="circle-cta" href="#campaign"><span>როგორ<br/>მუშაობს?</span><ArrowDownRight size={24}/></a></div><div className="opening-photo"><Image src="/media/waymart-storefront.jpg" alt="Way Mart-ის მარკეტი" fill priority sizes="(max-width: 800px) 100vw, 52vw"/><div className="photo-label">RECRUIT<br/>& WIN</div></div><div className="scroll-mark">SCROLL TO EXPLORE ↓</div></section>
<section className="statement" id="why"><div className="section-index">02</div><div className="statement-main"><p className="micro">YOUR FRIEND ON THE ROAD</p><h2>კარგი გუნდი<br/><span>მეგობრით<br/>იწყება.</span></h2></div><div className="statement-side"><p>Way Mart არის სოკარის მარკეტების ქსელი 70-ზე მეტ ავტოგასამართ სადგურზე — ექსკლუზიური პროდუქტებით, იტალიური ყავით, ჰოთდოგით, ცომეულით და მუდმივი შეთავაზებებით.</p><p>ახლა ამ გზაზე შენც შეგიძლია შემოხვიდე: ითამაშე, შეავსე განაცხადი და გაიცანი გუნდი, სადაც შენი დღეები მოძრაობაშია.</p><a className="arrow-link" href="https://sgp.ge/en/way-mart" target="_blank">ბრენდის ოფიციალური გვერდი <ArrowUpRight size={18}/></a></div></section>
<section className="reward-zone" id="campaign"><div className="reward-copy"><p className="micro">03 / WAYMART RECRUIT & WIN</p><h2>დაატრიალე.<br/><span>მიიღე.</span></h2><p>სამი დატრიალება გაშორებს შენს პირველ საჩუქარს. ითამაშე პირდაპირ აქ და გაიგე, რა გელოდება Way Mart-ის გუნდში შესვლის გზაზე.</p><div className="reward-steps"><b>01 <small>დატრიალება</small></b><b>02 <small>აპლიკაცია</small></b><b>03 <small>ბონუსი</small></b></div></div><RecruitWheel/></section>
<section className="roles-new" id="roles"><div className="roles-intro"><p className="micro">04 / OPEN ROLE</p><h2>შენი ახალი<br/><i>დასაწყისი.</i></h2><p>კამპანიის მიმდინარე პოზიციაა მოლარე-კონსულტანტი თბილისში — სრული განაკვეთი და 24-საათიანი ცვლის რეჟიმი.</p></div><div className="role-rail"><Role n="01" t="მოლარე-კონსულტანტი" d="თბილისი · სრული განაკვეთი · 24-საათიანი ცვლა"/><Role n="02" t="რას გააკეთებ" d="მომსახურება · სალარო · პროდუქტი · წესრიგი"/><Role n="03" t="რას მიიღებ" d="110–120₾ ცვლაში · ბონუსი 200–250₾ · დაზღვევა · ტრანსპორტი"/><a className="see-all" href={applyUrl} target="_blank">შეავსე<br/>აპლიკაცია <ArrowUpRight size={20}/></a></div></section>
<section className="shift" id="inside"><div className="shift-title"><p className="micro">05 / INSIDE THE SHIFT</p><h2>One day.<br/><i>Many stories.</i></h2></div><div className="shift-collage"><div className="collage-large"><Image src="/media/waymart-story-2.avif" alt="Way Mart-ის გუნდი" fill sizes="45vw"/><span>TEAM / 01</span></div><div className="collage-small"><Image src="/media/waymart-storefront.jpg" alt="Way Mart-ის ლოკაცია" fill sizes="25vw"/><span>PLACE / 02</span></div><div className="collage-copy">ყოველი ცვლა განსხვავებულია.<br/><strong>შენი ისტორია აქ იწყება.</strong></div></div></section>
<section className="join"><div className="join-top"><p className="micro">06 / TAKE THE NEXT STEP</p><span>COFFEE · HOTDOG<br/>· 50₾ VOUCHER</span></div><h2>დაატრიალე.<br/><i>შეავსე.</i><br/>შემოგვიერთდი.</h2><a className="apply-stamp" href={applyUrl} target="_blank">დაიწყე<br/>ახლა <ArrowUpRight size={24}/></a></section>
<footer><a className="wordmark" href="#start"><span className="mark">W</span><span>WAY<br/><b>MART</b></span></a><span>შენი მეგობარი გზაზე</span><div><a href="https://www.facebook.com/WayMartGeorgia/" target="_blank">FB</a><a href="https://www.tiktok.com/@waymart" target="_blank">TT</a></div></footer></main>}
function Role({n,t,d}:{n:string,t:string,d:string}){return <a className="role-line" href={applyUrl} target="_blank"><b>{n}</b><span><strong>{t}</strong><small>{d}</small></span><ArrowUpRight size={19}/></a>}
function RecruitWheel(){const [spins,setSpins]=useState(0);const [busy,setBusy]=useState(false);const [reward,setReward]=useState('');function spin(){if(busy||spins>=2)return;setBusy(true);const next=spins+1;setSpins(next);window.setTimeout(()=>{setReward(next===2?'50₾ ვაუჩერი':'ყავა ან ჰოთდოგი');setBusy(false)},950)}return <div className="wheel-card"><div className="wheel-top"><span>WAYMART / RECRUIT & WIN</span><b>{String(spins+1).padStart(2,'0')} / 02</b></div><div className="wheel-wrap"><div className={'wheel '+(busy?'turning':'')+' '+(spins===1?'second-spin':'')}><span>ყავა</span><span>სიურპრიზი</span><span>ჰოთდოგი</span><span>ბონუსი</span><span>კიდევ სცადე</span><span>ვაუჩერი</span></div><div className="wheel-center">{busy?'...':reward||'დაატრიალე'}</div><div className="wheel-pointer">▼</div></div><div className="wheel-result">{reward?<><strong>{reward}</strong><small>{spins===2?'შეავსე აპლიკაცია და გახსენი შენი ახალი დასაწყისი.':'პირველი საჩუქარი შენია. მეორე დატრიალება შემდეგ გელოდება.'}</small></>:<small>პირველი დატრიალება — ყავა ან ჰოთდოგი. მეორე — 50₾ ვაუჩერი.</small>}</div><button className="spin-button" onClick={spin} disabled={busy||spins>=2}>{busy?'იტრიალებს...':spins>=2?'ორი საჩუქარი გახსნილია':'დაატრიალე '+(spins+1)+' / 2'}</button><a className="apply-under" href={applyUrl} target="_blank">შეავსე აპლიკაცია <ArrowUpRight size={16}/></a></div>}
